version: '3.8'

services:
  #MySQL_hotdeal
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_HOTDEAL}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d  # 초기화 SQL 연결
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1" ]
      interval: 10s
      retries: 30
    networks:
      - hotdeal-network

  #Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hotdeal-network

  #RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
#      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 30
    networks:
      - hotdeal-network

  #Config-Service
  config-service:
    build:
      context: .
      dockerfile: config-service/Dockerfile
    ports:
      - "8888:8888"
    container_name: config-service
    environment:
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASSWORD}
    networks:
      - hotdeal-network

  #Eureka-Server
  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hotdeal-network

  apigateway-service:
    build:
      context: .
      dockerfile: apigateway-service/Dockerfile
    container_name: apigateway-service
    ports:
      - "8080:8080"
    depends_on:
      config-service:
        condition: service_started
      eureka-server:
        condition: service_started
    networks:
      - hotdeal-network

  #Hotdeal-Service
  hotdeal-service:
    build:
      context: .
      dockerfile: hotdeal-service/Dockerfile
    container_name: hotdeal-service
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
      apigateway-service:
        condition: service_started
      config-service:
        condition: service_started
    networks:
      - hotdeal-network

  #User-Service
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
      apigateway-service:
        condition: service_started
      config-service:
        condition: service_started
    networks:
      - hotdeal-network

  #Order-Service
  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
      apigateway-service:
        condition: service_started
      config-service:
        condition: service_started
    networks:
      - hotdeal-network

  #payment-Service
  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    container_name: payment-service
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
      apigateway-service:
        condition: service_started
      config-service:
        condition: service_started
    networks:
      - hotdeal-network


networks:
  hotdeal-network:
    driver: bridge